# Generated by Django 4.0.4 on 2022-05-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SertDiamonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1', models.IntegerField(verbose_name='id_1')),
                ('kod_t', models.IntegerField(verbose_name='код_т')),
                ('part', models.IntegerField(verbose_name='партия')),
                ('kod_r', models.CharField(max_length=6, verbose_name='код_случ')),
                ('nsert', models.CharField(max_length=10, verbose_name='номер_паспорта')),
                ('dsert', models.CharField(max_length=10, verbose_name='дата_паспорта')),
                ('ogr', models.CharField(max_length=25, verbose_name='огранка')),
                ('shape', models.CharField(max_length=25, verbose_name='shape')),
                ('DiametrMin', models.FloatField(verbose_name='DiametrMin')),
                ('DiametrMax', models.FloatField(verbose_name='DiametrMax')),
                ('sizes', models.FloatField(verbose_name='Размеры')),
                ('obshmass', models.FloatField(verbose_name='ОБЩМАССА')),
                ('carat', models.FloatField(verbose_name='масса')),
                ('pcs', models.IntegerField(verbose_name='штук')),
                ('col_r', models.CharField(max_length=4, verbose_name='цвет')),
                ('cla_r', models.CharField(max_length=4, verbose_name='чистота')),
                ('po_r', models.CharField(max_length=2, verbose_name='геом_парам')),
                ('flour', models.CharField(max_length=10, verbose_name='флуор')),
                ('comment', models.CharField(max_length=50, verbose_name='комент')),
                ('TotalDepth', models.FloatField(verbose_name='TotalDepth')),
                ('diametr', models.FloatField(verbose_name='diametr')),
                ('PavilDepth', models.FloatField(verbose_name='PavilDepth')),
                ('PavilAngle', models.FloatField(verbose_name='PavilAngle')),
                ('CrownHeight', models.FloatField(verbose_name='CrownHeight')),
                ('CrownAngle', models.FloatField(verbose_name='CrownAngle')),
                ('TableSize', models.FloatField(verbose_name='TableSize')),
                ('Girdle_max', models.FloatField(verbose_name='Girdle_max')),
                ('Girdle_min', models.FloatField(verbose_name='Girdle_min')),
                ('CuletSize', models.FloatField(verbose_name='CuletSize')),
                ('print', models.IntegerField(verbose_name='принт')),
                ('diamdev', models.FloatField(verbose_name='diamdev')),
                ('Weight', models.FloatField(verbose_name='Weight')),
                ('kod', models.FloatField(verbose_name='kod')),
                ('mras', models.FloatField(verbose_name='mras')),
                ('col_gia', models.CharField(max_length=20, verbose_name='col_gia')),
                ('cla_gia', models.CharField(max_length=10, verbose_name='cla_gia')),
                ('cut_gia', models.CharField(max_length=10, verbose_name='cut_gia')),
                ('res', models.CharField(max_length=20, verbose_name='res')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
