# Generated by Django 4.0.4 on 2022-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrsert', '0002_sertdiamonds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertdiamonds',
            name='slag',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
