# Generated by Django 4.0.4 on 2022-05-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(default=1, max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
